name: Notify Discord
on:
  issues:
    types: [opened]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Nueva issue abierta: ${{ github.event.issue.title }}"
