name: Discord Notify
on:
  workflow_call:
    # Definimos webhook_url como un secret
    secrets:
      webhook_url:
        description: 'Discord Webhook URL'
        required: true
    inputs:
      issue_number:
        description: 'Número de la issue'
        required: true
        type: number
      issue_title:
        description: 'Título de la issue'
        required: true
        type: string
      repository:
        description: 'Nombre completo del repositorio'
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          # La acción lee la URL desde esta var de entorno
          DISCORD_WEBHOOK: ${{ secrets.webhook_url }}
        with:
          # 'args' es el único input que acepta esta acción
          args: |
            Nueva issue en `${{ inputs.repository }}`:
            #${{ inputs.issue_number }} – ${{ inputs.issue_title }}
            Link: https://github.com/${{ inputs.repository }}/issues/${{ inputs.issue_number }}
