name: Shared CI
on:
  workflow_call:
    inputs:
      dotnet_version:
        type: string
        default: '8.0.x'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - run: dotnet build --configuration Release
